### PR TITLE
(doc) Fix spelling of GitHub

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by webbertakken** [comment]
Hi @gep13 thanks for your contribution.

For some reason the checks are not running. I'll have a look at it later and merge your request.

**Comment by webbertakken** [comment]
Since there's no activated license on your side i'll just quickly pick this one up in https://github.com/webbertakken/unity-actions/pull/22

**Comment by gep13** [comment]
@webbertakken what do you mean by activated license?

**Comment by webbertakken** [comment]
> @webbertakken what do you mean by activated license?

https://github.com/webbertakken/unity-actions/pull/19/checks?check_run_id=338080889

The test workflow was failing due to not having configured `UNITY_LICENSE` environment variable in your fork.

**Comment by gep13** [comment]
I am very confused as to why that would be required. Surely any checks that are required would run in the context of this repository, not on my fork. Also, this was a change to documentation, and small typo, so not sure why any additional checks would be required.

**Comment by webbertakken** [comment]
> Surely any checks that are required would run in the context of this repository, not on my fork. 

One would seem to think so, however this is not the case; the actions workflow actually runs on the repository/fork that made changes. I think this is to prevent potential malicious changes to actions, that could for example output the values of secrets of the origin repository.

As mentioned, your fix has been applied. Thank you for your contribution.

**Pull request closed without merging**
